version: '3'
services:

  wordpress-db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./wordpress-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "<mysql root password strings>"
      MYSQL_DATABASE: "<mysql database name>"
      MYSQL_USER: "<mysql username of database>"
      MYSQL_PASSWORD: "<mysql password strings of user level priviledge>"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306

  wordpress:
    image: wordpress:php8.0-apache
    depends_on:
      - wordpress-db
    restart: always
    volumes:
      - ./wordpress/html:/var/www/html
    environment:
      VIRTUAL_HOST: "<FQDN>"
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: "<mysql username of database>"
      WORDPRESS_DB_PASSWORD: "<mysql password strings of user level priviledge>"
      WORDPRESS_DB_NAME: "<mysql database name>"
    ports:
      - 80

  proxy:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    depends_on:
      - wordpress
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/dhparam.pem:/var/lib/ssl-proxy/dhparam.pem
      - ./proxy/crt/<certificate name>:/var/lib/certificate/<certificate name>
      - ./proxy/crt/<private key name>:/var/lib/certificate/<private key name>

