version: '3'
services:

  kanepon-db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: kanepon-db
    volumes:
      - ./kanepon-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: A3Q30sMC9O9AVHNH
      MYSQL_DATABASE: hSk5rr9V73IocAkD
      MYSQL_USER: 99RtKjSybxFVFjqh
      MYSQL_PASSWORD: sbclpjupUHczoS4s
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306

  kanepon:
    image: wordpress:php8.0-apache
    container_name: kanepon
    depends_on:
      - kanepon-db
    restart: always
    volumes:
      - ./kanepon/html:/var/www/html
    environment:
      VIRTUAL_HOST: kanepon
      WORDPRESS_DB_HOST: kanepon-db:3306
      WORDPRESS_DB_USER: 99RtKjSybxFVFjqh
      WORDPRESS_DB_PASSWORD: sbclpjupUHczoS4s
      WORDPRESS_DB_NAME: hSk5rr9V73IocAkD
    ports:
      - 80

  prx:
    image: nginx:latest
    container_name: prx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - kanepon
    volumes:
      - ./prx/nginx.conf:/etc/nginx/nginx.conf
      - ./prx/default.conf:/etc/nginx/conf.d/default.conf
      - ./prx/dhparam.pem:/var/lib/ssl-proxy/dhparam.pem
      - ./prx/crt/kanepon.com.crt:/var/lib/certificate/kanepon.com.crt
      - ./prx/crt/kanepon.com.key:/var/lib/certificate/kanepon.com.key

