version: '3'

services:

  web_4_certbot:
    container_name: web_4_certbot
    #image: nginx:1.19.2-alpine
    image: nginx:latest
    restart: always
    volumes:
      - ./letsencrypt/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/nginxConf:/etc/nginx/conf.d
      - ./letsencrypt/html:/var/www/html:wr
    #network_mode: host
    ports: 
      - 80:80

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes: 
      - ./letsencrypt/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/html:/var/www/html:wr
    command: ["--version"]
